name: Build Xaim App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Setup-Java (Android NDK standard)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Run Buildozer Compiler
      run: |
        export BUILDOZER_ALLOW_ORG_ERRORS=1
        buildozer android debug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: Xaim-Downloader-APK
        path: bin/*.apk
