name: Build Xaim App

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Java 11 Setup
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "11"


    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"


    - name: Android SDK Setup
      uses: android-actions/setup-android@v3


    - name: Accept Licenses
      run: |
        yes | sdkmanager --licenses || true


    - name: Install Android Packages
      run: |
        sdkmanager \
        "platform-tools" \
        "platforms;android-33" \
        "build-tools;33.0.2"


    - name: Dependencies
      run: |
        sudo apt update

        sudo apt install -y \
        git \
        zip \
        unzip \
        autoconf \
        automake \
        libtool \
        libtool-bin \
        pkg-config \
        gettext \
        python3-pip \
        python3-virtualenv


    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install "cython<3"


    - name: Buildozer Config
      run: |

        mkdir -p ~/.buildozer/android/platform

        echo "sdk.dir=$ANDROID_HOME"

        rm -rf ~/.buildozer/android/platform/android-sdk

        ln -s \
        $ANDROID_HOME \
        ~/.buildozer/android/platform/android-sdk


    - name: Clean
      run: |
        rm -rf .buildozer


    - name: Build APK
      run: |

        export JAVA_HOME=$JAVA_HOME_11_X64

        export ANDROID_HOME=/usr/local/lib/android/sdk

        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk

        buildozer android debug


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Xaim-Downloader-APK
        path: bin/*.apk